[package]
name = "lumina-latency-monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
celestia-grpc = { version = "0.9.0", features = ["tls-ring"] }
celestia-types = "0.17.0"
tokio = { version = "1.42", features = ["macros", "rt", "rt-multi-thread", "signal"] }
rand = "0.8.5"
hex = "0.4.3"
anyhow = "1.0"

clap = { version = "4.5", features = ["derive", "env"] }
csv = "1.3"
humantime = "2.1"
parse_duration = "2"
thiserror = "2.0"

[dev-dependencies]
tokio = { version = "1.42", features = ["rt", "rt-multi-thread", "macros"] }
