---
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'collector'
    metrics_path: /metrics
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    scheme: http
    static_configs:
      - targets:
          - 'otel-collector:8889'
  - job_name: 'core0'
    static_configs:
      - targets: ['core0:26660']
        labels:
          group: 'Core0'
  - job_name: 'core1'
    static_configs:
      - targets: ['core1:26660']
        labels:
          group: 'Core1'
  - job_name: 'core2'
    static_configs:
      - targets: ['core2:26660']
        labels:
          group: 'Core2'
  - job_name: 'core3'
    static_configs:
      - targets: ['core3:26660']
        labels:
          group: 'Core3'
