[book]
authors = ["Celestia Labs"]
language = "en"
multilingual = false
title = "Celestia App Specifications"

[output.html]
git-repository-url = "https://github.com/celestiaorg/celestia-app"

[rust]
edition = "2021"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
