name: dependabot-tidy

on:
  pull_request:
    branches: [main]
    paths:
      - '**/go.mod'
      - '**/go.sum'

permissions:
  contents: write
  pull-requests: write

jobs:
  tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 #v5.5.0
        with:
          go-version-file: "go.mod"

      - name: Run go mod tidy in all modules
        run: |
          find . -name 'go.mod' -execdir sh -c '
            echo "Running go mod tidy in $(pwd)"
            go mod tidy
          ' \;

      - name: Commit and push tidy changes (only Dependabot PRs)
#        if: github.event_name == 'pull_request' && github.actor == 'dependabot[bot]'
        run: |
          git config --global user.name "rach-id"
          git config --global user.email "chamirachid1@github.com"

          git config --global credential.helper store
          echo "https://oauth2:${{ secrets.DEPENDABOT_TIDY_TOKEN }}@github.com" > ~/.git-credentials
          
          git add .
          
          if git diff --cached --quiet; then
            echo "No changes to commit after go mod tidy."
            exit 0
          fi
          
          git commit -m "chore: run go mod tidy on all modules"
          git push "https://x-access-token:${{ secrets.DEPENDABOT_TIDY_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git" "HEAD:${{ github.head_ref }}"
