name: lint
on:
  workflow_call:

jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    timeout-minutes: 8
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 #v5.5.0
        with:
          go-version-file: "go.mod"
      - uses: technote-space/get-diff-action@f27caffdd0fb9b13f4fc191c016bb4e0632844af #v6.1.2
        with:
          # This job will pass without running if go.mod, go.sum, and *.go
          # wasn't modified.
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
      - uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 #v8.0.0
        with:
          version: v2.1.2
          args: --timeout 10m
          github-token: ${{ secrets.github_token }}
        if: env.GIT_DIFF

  hadolint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
    - uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: docker/standalone.Dockerfile
    - uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: docker/multiplexer.Dockerfile
    - uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: docker/txsim/Dockerfile

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      - uses: celestiaorg/.github/.github/actions/yamllint@98f519843a1bade938e5604202df600aa0717aa8 #v0.6.3
