name: lint
on:
  workflow_call:

jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    timeout-minutes: 8
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 #v4.3.1
      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 #v6.0.0
        with:
          go-version-file: "go.mod"
      - uses: technote-space/get-diff-action@f27caffdd0fb9b13f4fc191c016bb4e0632844af #v6.1.2
        with:
          # This job will pass without running if go.mod, go.sum, and *.go
          # wasn't modified.
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
      - run: go tool golangci-lint run --timeout 10m
        if: env.GIT_DIFF

  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 #v4.3.1
      - uses: technote-space/get-diff-action@f27caffdd0fb9b13f4fc191c016bb4e0632844af #v6.1.2
        with:
          PATTERNS: |
            docker/**
      - uses: hadolint/hadolint-action@v3.3.0
        if: env.GIT_DIFF
        with:
          dockerfile: docker/standalone.Dockerfile
      - uses: hadolint/hadolint-action@v3.3.0
        if: env.GIT_DIFF
        with:
          dockerfile: docker/multiplexer.Dockerfile
      - uses: hadolint/hadolint-action@v3.3.0
        if: env.GIT_DIFF
        with:
          dockerfile: docker/txsim/Dockerfile

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 #v4.3.1
      - uses: technote-space/get-diff-action@f27caffdd0fb9b13f4fc191c016bb4e0632844af #v6.1.2
        with:
          PATTERNS: |
            **/*.yml
            **/*.yaml
      - uses: celestiaorg/.github/.github/actions/yamllint@9ee03305d3cc6cf520b7895436429aa853b58e70 #v0.6.4
        if: env.GIT_DIFF
