name: Protobuf
# Protobuf runs buf (https://buf.build/) lint and generate
# This workflow is only run when a .proto file has been changed
on:
  pull_request:
    paths:
      - "**.proto"
jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: lint
        run: make proto-lint
  proto-gen:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: "Check protobuf generated code matches committed code"
        run: |
          set -euo pipefail

          make proto-gen

          if ! git diff --stat --exit-code ; then
            echo ">> ERROR:"
            echo ">>"
            echo ">> Protobuf generated code requires update (either tools or .proto files may have changed)."
            echo ">> Ensure your tools are up-to-date, re-run 'make proto-gen' and update this PR."
            echo ">>"
            exit 1
          fi
  # add this back when we start using versioning
  # breakage:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: check-breakage
  #       run: make proto-check-breaking
