name: test-e2e

on:
  push:
    branches:
      - main
    paths:
      - "**.go"
      - go.mod
      - go.sum

jobs:
  test-e2e-docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        testcase:
          - TestE2ESimple
          - TestStateSync

    name: Run ${{ matrix.testcase }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"

      - name: Run E2E test
        env:
          CELESTIA_TAG: v4.0.0-arabica # TODO: dynamically assign this based on images built on this PR.
        run: |
          make test-e2e test=${{ matrix.testcase }}

  test-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          fetch-depth: 0
          ref: main
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 #v5.5.0
        with:
          go-version-file: "go.mod"
      - name: Setup kubeconfig
        env:
          KUBECONFIG_FILE: ${{ secrets.KNUU_DEV_KUBECONFIG_FILE }}
        run: |
          mkdir -p $HOME/.kube
          echo "${KUBECONFIG_FILE}" > $HOME/.kube/config
      - name: Run e2e tests
        run: make test-e2e

      - name: If the e2e test fails, notify Slack channel #e2e-test-failures
        if: failure()
        uses: ravsamhq/notify-slack-action@be814b201e233b2dc673608aa46e5447c8ab13f2 #v2.5.0
        with:
          status: ${{ job.status }}
          token: ${{ secrets.GITHUB_TOKEN }}
          notification_title: "E2E test failure"
          message_format: "{emoji} *{workflow}* {status_message} in <{run_url}|{repo}>"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_E2E_TEST_FAILURES }}
